### ISSUE TITLE
Tweak logLevels

### ISSUE THREAD

**Issue by danielloader** [rudemex/signale-logger#2]
**Is your feature request related to a problem? Please describe.**
Currently I can't get a logLevel that shows everything EXCEPT debug log entries. 

**Describe the solution you'd like**
Change log levels to be in line with other projects:

Taking python's logging levels you get something along the lines of:
 
```
CRITICAL: 50
ERROR: 40
WARNING: 30
INFO: 20
DEBUG: 10
NOTSET: 0
```

That way if the log level is set to info, debug doesn't show, if it's set to debug, debug and above show.

**Comment by danielloader** [comment]
This seems to have been fixed in someone elses single fix fork, maybe worth coordinating if you're intending to maintain this now?
https://github.com/klaussinani/signale/issues/96#issuecomment-616970762

**Comment by rudemex** [comment]
hi @danielloader  the last version implemented already contemplates the above mentioned adjustment, however, expanded to the possibility of reorganizing the log levels from the same package.json, in case it is required to add, remove, or move a log level.

https://github.com/rudemex/signale-logger/releases/tag/v1.5.0

**Comment by danielloader** [comment]
That's great, closing!

**Comment by danielloader** [comment]
Just tried it with:
```
const options = { logLevel: "info" };
const logger = new Signale(options);

logger.info("example");
logger.debug("debug example");
```

And nothing shows, but running:
```
const options = { };
const logger = new Signale(options);

logger.info("example");
logger.debug("debug example");
```
Both display.

Can you replicate this?

**Comment by danielloader** [comment]
https://repl.it/@danielloader/IrritatingUntriedCodeview

Thrown up a repl.it to demonstrate the issue. Might help.

**Comment by rudemex** [comment]
Hi @danielloader , thanks for the help, I already detected what is the problem that is not taking the logLevel from the configuration, this week I'm a little busy, and I hope to have fixed the bug this weekend.

Greetings

**Comment by jcristovao** [comment]
Hey @rudemex , do you still have plans to address this?

Thank you!

**Comment by rudemex** [comment]
hi @jcristovao yes, I plan to take these adjustments, but unfortunately not soon.

If anyone is interested in collaborating, you are welcome and I will do my best to make the PRs as soon as possible.

**Comment by jcristovao** [comment]
Hey @rudemex , I took a look into it, and it seems the fix was pretty easy, I've made a small PR
