### ISSUE TITLE
Add Sentry as optional logging

### ISSUE THREAD

**Issue by Pacerino** [rudemex/signale-logger#6]
**Is your feature request related to a problem? Please describe.**
I would like to monitor my errors through Sentry

**Describe the solution you'd like**
An optional option to add a Sentry DSN so that errors are also sent to Sentry

**Additional context**
I have not found a way to add a hook into the error function. Is this possible?

**Comment by rudemex** [comment]
Hi @Pacerino, how are you? this dependency is only for logging, if you need to trace the requests and responses, I recommend that you do Jaeger, it will allow you to see the complete flow with its status of each call that is made in your application.
